Repository kneron/ONNX_Convertor, pull requests merged in 2020-10, with the labels that each got.

#16 support 2 dim's add-mul fusing into bn
  optimizer_scripts/tools/fusing.py
Labels: enhancement

#17 check if input_shape dim is 4 and has the same dim with mul_node's ch…
  optimizer_scripts/tools/fusing.py
Labels: enhancement

#18 tflite2onnx update
  tflite-onnx/README.md
  tflite-onnx/onnx_tflite/aact_layers.py
  tflite-onnx/onnx_tflite/core_layers.py
  tflite-onnx/onnx_tflite/merg_layers.py
  tflite-onnx/onnx_tflite/tree_structure.py
Labels: bug, enhancement

#20 Fix bug in add_bn
  optimizer_scripts/onnx2onnx.py
Labels: bug

#21 update
  optimizer_scripts/tools/combo.py
  optimizer_scripts/tools/replacing.py
  tflite-onnx/onnx_tflite/conv_layers.py
  tflite-onnx/onnx_tflite/pool_layers.py
Labels: bug, enhancement

#22 Set split ConvTranspose as an optional feature in onnx2onnx
  optimizer_scripts/onnx2onnx.py
  optimizer_scripts/tools/combo.py
Labels: enhancement

#24 tool for adding shift conv for add_norm
  optimizer_scripts/editor.py
  optimizer_scripts/tools/other.py
Labels: enhancement
