Repository kneron/ONNX_Convertor, pull requests merged in 2020-07, with the labels that each got.

#2 Support auto_pad shape inference for Conv.
  optimizer_scripts/tools/helper.py
  optimizer_scripts/tools/other.py
Labels: bug, enhancement

#4 check value_info exists before remove it
  optimizer_scripts/tools/replacing.py
Labels: bug

#6 first add tflite-onnx
  tflite-onnx/.gitattributes
  tflite-onnx/README.txt
  tflite-onnx/example/example.tflite
  tflite-onnx/generate_onnx.py
  tflite-onnx/onnx_tflite/aact_layers.py
  tflite-onnx/onnx_tflite/base_layer.py
  tflite-onnx/onnx_tflite/conv_layers.py
  tflite-onnx/onnx_tflite/core_layers.py
  tflite-onnx/onnx_tflite/flatc/flatc
  tflite-onnx/onnx_tflite/flatc/schema.fbs
  tflite-onnx/onnx_tflite/merg_layers.py
  tflite-onnx/onnx_tflite/pool_layers.py
  tflite-onnx/onnx_tflite/tflite2onnx.py
  tflite-onnx/onnx_tflite/utils.py
Labels: enhancement

#8 TFlite convertor stable version
  .gitignore
  tflite-onnx/README.md
  tflite-onnx/README.txt
  tflite-onnx/generate_onnx.py
  tflite-onnx/onnx_tflite/aact_layers.py
  tflite-onnx/onnx_tflite/base_layer.py
  tflite-onnx/onnx_tflite/conv_layers.py
  tflite-onnx/onnx_tflite/core_layers.py
  tflite-onnx/onnx_tflite/merg_layers.py
  tflite-onnx/onnx_tflite/pool_layers.py
  tflite-onnx/onnx_tflite/tflite2onnx.py
Labels: enhancement
