Repository kneron/ONNX_Convertor, pull requests merged in 2020-12, with the labels that each got.

#28 Add pytorch preprocess script.
  keras-onnx/onnx_keras/merg_layers.py
  optimizer_scripts/pytorch_exported_onnx_preprocess.py
Labels: bug, enhancement

#29 Fix caffe prelu
  caffe-onnx/onnx_caffe/aact_layers.py
Labels: bug

#30 Add BN constant folding.
  optimizer_scripts/tools/constant_folding.py
Labels: enhancement

#31 fix crash issue while gemm at top
  optimizer_scripts/tools/removing_transpose.py
Labels: bug

#33 reset the input when deleted node is an input,
  optimizer_scripts/tools/modhelper.py
Labels: enhancement

#32 Support mxnet exported onnx.
  optimizer_scripts/onnx1.3to1.4.py
Labels: enhancement

#35 Keep output order while cutting nodes.
  optimizer_scripts/tools/other.py
Labels: enhancement

#36 Fix keras concate axis conversion.
  keras-onnx/onnx_keras/merg_layers.py
Labels: bug

#37 Fix keras output order.
  keras-onnx/onnx_keras/frontend.py
  keras-onnx/onnx_keras/preprocess.py
Labels: bug

#38 support 1.SpaceToDepth 2.DepthToSpace 3.Maximum
  tflite-onnx/README.md
  tflite-onnx/onnx_tflite/core_layers.py
  tflite-onnx/onnx_tflite/tree_structure.py
Labels: enhancement
