Repository kneron/ONNX_Convertor, pull requests merged in 2021-01, with the labels that each got.

#39 1.tflite support leaky_relu 2.show unsupported op type name 3.suppor…
  tflite-onnx/onnx_tflite/aact_layers.py
  tflite-onnx/onnx_tflite/tree_structure.py
Labels: bug, enhancement

#40 Logging
  tflite-onnx/README.md
  tflite-onnx/onnx_tflite/base_layer.py
  tflite-onnx/onnx_tflite/conv_layers.py
  tflite-onnx/onnx_tflite/tflite2onnx.py
  tflite-onnx/onnx_tflite/tree_structure.py
Labels: documentation, enhancement

#41 Fix bugs when consecutinve gemm fusing happens.
  optimizer_scripts/tools/fusing.py
  optimizer_scripts/tools/modhelper.py
Labels: bug

#42 fix keras 4d softmax wrong result issue
  keras-onnx/onnx_keras/core_layers.py
Labels: bug
